name: webserver
description: Restful API to serve Studentifier's requests
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  args: ^2.0.0
  shelf: ^1.1.0
  supabase: ^1.1.0
  intl: ^0.17.0